#!/bin/bash
# Konfigurationsdatei aus Umgebungsvariablen erzeugen

cat > /etc/mtv_cli.conf <<EOF
[CONFIG]
MSG_LEVEL: ${MSG_LEVEL:-INFO}
DATE_CUTOFF: ${DATE_CUTOFF:-30}
DAUER_CUTOFF: ${DAUER_CUTOFF:-5}
NUM_DOWNLOADS: ${NUM_DOWNLOADS:-2}
ZIEL_DOWNLOADS: ${ZIEL_DOWNLOADS:-/downloads/{Sender}_{Datum}_{Thema}_{Titel}.{ext}}
CMD_DOWNLOADS: ${CMD_DOWNLOADS:-wget -q -c -O '{ziel}' '{url}'}
CMD_DOWNLOADS_M3U: ${CMD_DOWNLOADS_M3U:-wget -q -O - '{url}' | grep '^http' | wget -q -O '{ziel}' -i -}
QUALITAET: ${QUALITAET:-LOW}

[WEB]
PORT: ${WEB_PORT:-8026}
HOST: ${WEB_HOST:-0.0.0.0}
EOF

/update-download-loop &
LOOP_PID=$!
/usr/local/bin/mtv_web.py
kill $LOOP_PID
