#!/bin/bash
INTERVAL_H=${UPDATE_INTERVAL:-24}
SLEEP_AFTER_UPDATE=$(( INTERVAL_H - 1 ))

while true ; do
  if [[ $(find /data/db/ -type f -mmin '+59' | wc -l) -gt 0 ]] ; then
    /usr/local/bin/mtv_cli.py -A
  fi
  sleep 1h
  /usr/local/bin/mtv_cli.py -D
  sleep "${SLEEP_AFTER_UPDATE}h"
done
